[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["libnss3", "libxss1", "libasound2", "libatk-bridge2.0-0", "libgtk-3-0", "libgbm-dev"]

[phases.install]
cmds = [
  "npm install -g corepack@latest",
  "corepack enable",
  "pnpm install --frozen-lockfile",
  "npx playwright install chromium"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm run start"
