[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g corepack@latest",
  "corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[start]
cmd = "pnpm run start"
